# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details

language: php 
php: 
 - 5.5

sudo: false

env:
 - DB=MYSQL CORE_RELEASE=master
 - DB=PGSQL CORE_RELEASE=master

matrix:
  include:
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=master

before_script:
 - phpenv rehash
 - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
 - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
 - cd ~/builds/ss

script: 
 - phpunit translatable/tests/
